### ISSUE TITLE
Transfer Serilog.Formatting.Log4Net to the Serilog Contrib organization

### ISSUE THREAD

**Issue by 0xced** [serilog-contrib/home#1] opened 2021-06-06 16:25 UTC
I would like to transfer my project [Serilog.Formatting.Log4Net](https://github.com/0xced/serilog-formatting-log4net/)  to the Serilog Contrib organization. I haven't released version 1.0.0 yet (only 1.0.0-rc.2) and I think it might be a good idea to release it once the project is transferred.

Should I simply initiate the transfer to the serilog-contrib GitHub organization or is there some kind of approval first?

**Comment by augustoproiete** [comment] 2021-06-06 17:17
Awesome, Cédric!

For **GitHub**, this is a multi-step operation due to how GitHub manages permissions for organizations (i.e. GitHub doesn't let me give you permission to transfer the repo directly to the org).

1. Transfer the repo to my user **augustoproiete**
2. I transfer it to the [Serilog Contrib](https://github.com/serilog-contrib) organization
3. You accept the invite to join the organization (you should have received an email)
4. I add you as admin in the repo, within the org

For **NuGet**, open the "Manage" package UI for your packages on nuget.org and add the user **serilog-contrib** as an additional owner of the nuget package.

**Comment by augustoproiete** [comment] 2021-06-06 18:33
You're all set!

- :white_check_mark: GitHub repo to transferred [serilog-contrib/serilog-formatting-log4net](https://github.com/serilog-contrib/serilog-formatting-log4net)
- :white_check_mark: NuGet package added to [cake-contrib](https://www.nuget.org/profiles/serilog-contrib)

Thanks!

**Closed as completed by augustoproiete** 2021-06-06 18:34 UTC

**Comment by 0xced** [comment] 2021-06-06 19:54
Great! Could you add the `serilog-contrib` organization to [Codacy](http://codacy.com)? I got this error when trying to add it myself:
> Only organization owners can add organizations to Codacy. Reach out to an owner of serilog-contrib and ask them to add the organization.

**Comment by augustoproiete** [comment] 2021-06-06 19:58
I think I've added. Let me know if there's any step I missed:

![image](https://user-images.githubusercontent.com/177608/120938291-54a8e800-c6e8-11eb-9bd7-87c8b78a30e1.png)

![image](https://user-images.githubusercontent.com/177608/120938294-583c6f00-c6e8-11eb-9d87-b650151f1441.png)

**Comment by 0xced** [comment] 2021-06-06 20:06
I'm still unable to access anything on Codacy. Maybe you need to [add me](https://docs.codacy.com/organizations/managing-people/) as member? (It's the first time I use Codacy with an organization.)

**Comment by augustoproiete** [comment] 2021-06-06 20:32
I've added you to the org within Codacy - give it a try - but I suspect the issue is that Codacy is confused with the move of the repo from your user to the org:

![image](https://user-images.githubusercontent.com/177608/120939159-00eccd80-c6ed-11eb-9bc2-a8520146823b.png)

Maybe you need to remove the repo from your own user/organization within Codacy so that it can let me add the repo to the serilog-contrib Codacy org?

**Comment by 0xced** [comment] 2021-06-07 07:56
I figured it out! I went to https://app.codacy.com/gh/0xced/serilog-formatting-log4net/settings in order to unregister the repository then I was able to add it to the serilog-contrib organization. 🎉

**Comment by 0xced** [comment] 2021-08-18 18:50
Hey @augustoproiete, can you login to https://dashboard.stryker-mutator.io/repos/serilog-contrib and enable the github.com/serilog-contrib/serilog-formatting-log4net repository in order to get a dashboard API key?

I tried but unfortunately I only see my repos under `0xced`, not under `serilog-contrib`.

**Comment by augustoproiete** [comment] 2021-08-18 18:56
@0xced Done. Let me know if you need anything else or if I need to generate an API key on your behalf.

![image](https://user-images.githubusercontent.com/177608/129955805-4319d393-6bc6-4b10-8d83-dca88b025196.png)

**Comment by 0xced** [comment] 2021-08-18 19:08
Thanks for the very quick response!

No need to generate an API key, I can now switch to `serilog-contrib` (I could not before) so I was able to generate an API key. <img width="498" alt="CleanShot 2021-08-18 at 20 58 18@2x" src="https://user-images.githubusercontent.com/51363/129956281-57260d96-d2e6-404e-a7c1-d519c4bb7b86.png">

And the mutation report was successfully uploaded to https://dashboard.stryker-mutator.io/reports/github.com/serilog-contrib/serilog-formatting-log4net/ed7885c0ce6dbbea8f1ba95a3fcd41c65f28d97e 🥳

**Comment by augustoproiete** [comment] 2021-08-18 19:54
Perfect. The mutation report looks great! :star_struck: Adding to my list of things to add to my OSS projects
